Document: kannasaver
Title: Debian kannasaver Manual
Author: <insert document author here>
Abstract: This manual describes what kannasaver is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/kannasaver/kannasaver.sgml.gz

Format: postscript
Files: /usr/share/doc/kannasaver/kannasaver.ps.gz

Format: text
Files: /usr/share/doc/kannasaver/kannasaver.text.gz

Format: HTML
Index: /usr/share/doc/kannasaver/html/index.html
Files: /usr/share/doc/kannasaver/html/*.html
