.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH KANNASAVER 1 "June  19, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
Kannasaver \- Japanese character screensaver for KDE 4
.SH SYNOPSIS
.B kannasaver.kss
[Qt-options] [KDE-options] [options]
.SH DESCRIPTION
This manual page documents briefly the
.B kannasaver.kss
command. Kannasaver is usually run through the KDE Systemsettings
.B Display and Monitor -> Screensaver
module.
.PP
.SH GENERAL OPTIONS
.TP
.B \-\-help
Show help about options.
.TP
.B \-\-help-qt
Show Qt specific options.
.TP
.B \-\-help-kde
Show KDE specific options.
.TP
.B \-\-help-all
Show all options.
.TP
.B \-\-author
Show author information.
.TP
.B \-v, \-\-version
Show version information.
.TP
.B \-\-license
Show license information
.TP
.B \-\-
End of options.
.PP
.SH OPTIONS
.TP
.B \-\-setup
Setup Kannasaver
.TP
.B \-\-window-id wid
Run in the specified XWindow
.TP
.B \-\-root
Run in the root XWindow
.TP
.B \-\-demo
Start Kannasaver in demo mode (default)
.SH AUTHOR
Kannasaver was written by Mathias Homann and is now maintained
by Frederik Schwarzer.
.PP
This manual page was written by Frederik Schwarzer <schwarzerf@gmail.com>,
for the Debian project (and may be used by others).
